name: Evil Monkey Labs
subtitle: Code and related ramblings.

# Absolute base URL for this site without trailing slash
url: http://blog.evilmonkeylabs.com

# Absolute URL of feed.
# You may want to change this URL to point to a feedburner feed.
feed: http://blog.evilmonkeylabs.com

# Author element in atom feed. Optional.
# If email is supplied, name is required.
author:
  name: Brendan W. McAdams
  email: bwmcadams+blog@evilmonkeylabs.com

safe:        true
auto:        true
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         true
pygments:    true
markdown:    maruku
permalink:   pretty
paginate:    3

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []
